### ISSUE TITLE
Problem with webpack 5

### ISSUE THREAD

**Issue by cristian-sima** [alleyinteractive/webpack-git-hash#13]
Hi,

I tried to upgrade to webpack 5 and I got this problem:

![image](https://user-images.githubusercontent.com/12199042/113440065-60c8ae80-93f4-11eb-9229-aec9451f6a94.png)

**Comment by cristian-sima** [comment]
Changed output.filename to [name]-9d45379.js
D:\workspace\src\github.com\cristian-sima\sidemate\node_modules\webpack-git-hash\index.js:176
    compiler.plugin('done', this.cleanupFiles);
             ^

TypeError: compiler.plugin is not a function
    at WebpackGitHash.apply (D:\workspace\src\github.com\cristian-sima\sidemate\node_modules\webpack-git-hash\index.js:176:14)
    at createCompiler (D:\workspace\src\github.com\cristian-sima\sidemate\node_modules\webpack\lib\webpack.js:71:12)
    at create (D:\workspace\src\github.com\cristian-sima\sidemate\node_modules\webpack\lib\webpack.js:118:16)
    at webpack (D:\workspace\src\github.com\cristian-sima\sidemate\node_modules\webpack\lib\webpack.js:142:32)
    at f (D:\workspace\src\github.com\cristian-sima\sidemate\node_modules\webpack\lib\index.js:54:15)
    at Object.<anonymous> (D:\workspace\src\github.com\cristian-sima\sidemate\server.js:19:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

**Comment by cristian-sima** [comment]
@alleyinteractive-ops any way to fix this?

**Comment by cristian-sima** [comment]
For those who have the same problem I managed to fix it by creating a new script for version 5. You can find it here https://github.com/cristian-sima/webpack-git-hash-updater
